### ISSUE TITLE
brisk

### ISSUE THREAD

**Issue by guofengw** [baidu/ICE-BA#3]
Hi,
when i compile the codes, i find that it can not find some include files about brisk, 
such as #include <brisk/internal/score-calculator.h>,
so how to find them? Thanks.

**Comment by michaelczhou** [comment]
`ICE-BA-master/Frontend/feature_utils.h:24:45: fatal error: brisk/internal/score-calculator.h: 没有那个文件或目录`
I have the same problem...how to slove it?

**Comment by Zekegao** [comment]
I guess this is a brisk lib, so I try install some, possible make install this : 
https://github.com/gwli/brisk.git

run ./build.sh, it's work, no error.(there will be errors again most possible when you run, waiting a official suggest)

But, I still cannot run the ./run_ice_ba.sh with some errors about databag.

E0620 00:54:23.577726 30977 EuRoC_test.cpp:356] "/MH_03_medium/mav0/cam0" is not a directory

so, good luck.

And, thx authors, it's awesome.

**Comment by wangjio** [comment]
Yes,it's a brisk lib, https://github.com/gwli/brisk.git. I'll update our readme soon. @guofengw @michaelczhou  
Make sure your EuRoC directory structure is same to the origin EuRoC dataset from https://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets#downloads. @Zekegao 
For example, if you want to run MH_03_medium, download the origin data, it should be a folder called mav0 after decompressing the MH_03_medium.zip, paste it into a folder created by yourself called MH_03_medium, maybe it absolute path is "~/dataset/MH_03_medium", then your scripts should be:

EuRoC_PATH=~/dataset
mkdir $EuRoC_PATH/result
cmd="./bin/ice_ba --imgs_folder $EuRoC_PATH/MH_03_medium --start_idx 0 --end_idx -1 --iba_param_path config/param.txt  --gba_camera_save_path $EuRoC_PATH/result/MH_03_medium.txt"
echo $cmd
eval $cmd

**Comment by Zekegao** [comment]
@wangjio Thank you very much~awesome work!
I think my error because of rosbag. I will try again.
If CVD is necessary? This one?

wget http://www.edwardrosten.com/cvd/libcvd-20150407.tar.gz
tar vxf libcvd-20150407.tar.gz
cd libcvd-20150407
export CXXFLAGS=-D_REENTRANT
./configure --without-ffmpeg
make
make install

**Comment by Zekegao** [comment]
It's working. The databag should be .zip, I used a rosbag. Thx @wangjio  
![screenshot from 2018-06-20 12 35 09](https://user-images.githubusercontent.com/25146198/41637441-82135008-7486-11e8-812c-07731b1f7d56.png)

**Comment by wangjio** [comment]
The question has been solved.
