### ISSUE TITLE
Is loop closure supported? If so, how to turn loop closure on?

### ISSUE THREAD

**Issue by highlightz** [baidu/ICE-BA#6]

**Comment by liuhaomin** [comment]
Yes, ICE-BA supports loop closure by Solver::PushRelativeConstraint. In our experiments, we extract ORB features for each keyframe, estimate the relative pose from feature matches between keyframes at the loop, and push the relative constraint to ICE-BA. Unfortuanately it is not included in this repo. We just provide a simple optic flow based frontend. You need to impelment the loop detection and relative pose estimation to enable loop closure. Sorry for that...

**Comment by highlightz** [comment]
Got it, thank you.

**Comment by wangjio** [comment]
The question has been solved.
