### ISSUE TITLE
numerical stability

### ISSUE THREAD

**Issue by DahaiHigh** [baidu/ICE-BA#7]
hi, i want to ask for the numerical stability in optimization when constructing the sparse structure Sx = d

**Comment by liuhaomin** [comment]
Do you mean the precision of S and d, or the precision of solving Sx = d?

**Comment by DahaiHigh** [comment]
## in general
   local BA marginalize will generate Sx = d which S is dense matrix.
## your solution 
  give sub-track to construct sparse Sx = d, the method reduce constraints. 
so i want to know whether the tips make optimization(LM or GN) non convergence sometimes?

**Comment by liuhaomin** [comment]
Indeed that is a problem for those points with too small parallax. Marginalizing such points will results in numerical instability and sub-track will make it worse. We do not marginalize such sub-tracks. If the information garthered on a sub-track is too small (less than the threshold *epsdST*), it will be treated as a fixed point and not be marginalized for Schur complement construction. And for back substitution performed on the original tracks, we also check the information garthered on the original track using another threshold *espd*, and do not update the ill-conditioned points.

The corresponding codes are at https://github.com/baidu/ICE-BA/blob/7fe5fcf0d33396d2f775d45aaa9d85c1ebda363b/Backend/BundleAdjustment/LocalBundleAdjustorGN.cpp#L899

**Comment by DahaiHigh** [comment]
Got it, thank you

**Comment by wangjio** [comment]
The question has been solved.
